config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: "users/registrations"
  }

  root "home#index"
  get "home/index"

  get "hashtags/index"
  get "hashtags/show"

  get "users/index"
  get "users/show"
  get "users/new"
  get "users/create"
  get "users/edit"
  get "users/update"
  get "users/destroy"

  get "profiles/index"
  get "profiles/show"

  get "posts/index"
  get "posts/show"

  resources :profiles, only: [ :index, :show, :new, :create, :edit, :update, :destroy ]
  resources :profiles, only: [ :show ] do
    post :follow, to: "follows#create", on: :member
    delete :unfollow, to: "follows#destroy", on: :member
  end

  resources :posts, only: [ :index, :show, :new, :create, :edit, :update, :destroy ]
  resources :posts do
    resources :comments, only: [ :create, :edit, :update, :destroy ]
  end
  resources :posts do
    resources :likes, only: [ :create, :destroy ]
  end
  resources :users, only: [ :index, :show, :new, :create, :edit, :update, :destroy ]
  resources :hashtags, only: [ :index, :show ]
  resources :comments, only: [ :edit, :update, :destroy ]



  get "up" => "rails/health#show", as: :rails_health_check
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    if user.admin?
      # Permisos para el administrador
      can :manage, :all
      return
    end

    # Permite a cualquier usuario (incluso no autenticado) ver perfiles
    can :read, Profile
    can :read, User

    # Solo si el usuario está logueado
    return unless user.present?

    # Permisos para su propio perfil y cuenta
    can :manage, User, id: user.id
    can :manage, Profile, user_id: user.id
    can :manage, Post, profile: { user_id: user.id }
    can :create, Post, profile: { user_id: user.id }
    can :create, Comment
    can :manage, Comment, profile: { user_id: user.id }
    can [ :create, :destroy ], Like, profile_id: user.profile.id if user.profile

    can :follow, Profile do |profile|
      user.present? && user.profile != profile
    end
    can :unfollow, Profile do |profile|
      user.present? && user.profile.following.include?(profile)
    end




    # (Agrega más permisos aquí si usas posts, comentarios, etc.)
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/block.rb
class Block < ApplicationRecord
  belongs_to :blocker, class_name: "User"
  belongs_to :blocked, class_name: "User"
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
  belongs_to :profile
  has_many :likes, as: :likeable, dependent: :destroy
  validates :body, presence: true
end

app/models/follow.rb
class Follow < ApplicationRecord
  belongs_to :follower
  belongs_to :followed
  belongs_to :follower, class_name: "Profile"
  belongs_to :followed, class_name: "Profile"
end

app/models/hashtag.rb
class Hashtag < ApplicationRecord
    has_many :post_hashtags
    has_many :posts, through: :post_hashtags
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :profile
  belongs_to :likeable, polymorphic: true
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :profile
  has_many :comments, dependent: :destroy
  has_many :likes, as: :likeable, dependent: :destroy
  has_many :post_hashtags, dependent: :destroy
  has_many :hashtags, through: :post_hashtags
  has_many :saved_posts, dependent: :destroy
  has_many :saved_by_users, through: :saved_posts, source: :user
  validates :image_url, presence: true
  validates :description, presence: true, length: { maximum: 500 }
end

app/models/post_hashtag.rb
class PostHashtag < ApplicationRecord
  belongs_to :post
  belongs_to :hashtag
end

app/models/profile.rb
class Profile < ApplicationRecord
  before_validation :set_default_avatar, on: :create

  validates :username, presence: true, uniqueness: true

  belongs_to :user
  has_many :posts, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy

  has_many :follower_relationships,
           class_name: "Follow",
           foreign_key: "followed_id",
           dependent: :destroy
  has_many :followers,
           through: :follower_relationships,
           source: :follower

  has_many :following_relationships,
           class_name: "Follow",
           foreign_key: "follower_id",
           dependent: :destroy
  has_many :following,
           through: :following_relationships,
           source: :followed

  private

  def set_default_avatar
    if self.avatar_url.blank?
      self.avatar_url = "https://img.freepik.com/free-vector/blue-circle-with-white-user_78370-4707.jpg?ga=GA1.1.1991389944.1748048473&semt=ais_hybrid&w=740"
    end
  end
end

app/models/saved_post.rb
class SavedPost < ApplicationRecord
  belongs_to :user
  belongs_to :post
end

app/models/user.rb
class User < ApplicationRecord
  #has_secure_password
  # Devise authentication modules
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :email, presence: true, uniqueness: true
  validates :password, presence: true

  has_one :profile, dependent: :destroy
  has_many :blocks_given, class_name: "Block", foreign_key: "blocker_id"
  has_many :blocked_users, through: :blocks_given, source: :blocked
  has_many :blocks_received, class_name: "Block", foreign_key: "blocked_id"
  has_many :blockers, through: :blocks_received, source: :blocker
  has_many :saved_posts
  has_many :favorite_posts, through: :saved_posts, source: :post

  accepts_nested_attributes_for :profile
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/hashtags_helper.rb
module HashtagsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-primary mb-4">
  <div class="container-fluid">
    <a class="navbar-brand" href="/"><strong>RedSocial</strong></a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarNav">
      <!-- Enlaces de navegación (izquierda) -->
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <%= link_to "Posts", posts_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Profiles", profiles_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Users", users_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Hashtags", hashtags_path, class: "nav-link" %>
        </li>
      </ul>

      <!-- Botones de autenticación (derecha) -->
      <ul class="navbar-nav ms-auto">
        <% if user_signed_in? && current_user.profile %>
          <li class="nav-item d-flex align-items-center me-3">
            <% if current_user.admin? %>
              <div class="navbar-text me-2">
                <strong>Admin</strong>
              </div>
            <% end %>
            <%= link_to profile_path(current_user.profile), class: "nav-btn p-0" do %>
              <button type="button" class="btn btn-outline-light" style="padding: 2px; gap: 10px; display: flex; align-items: center;">
                <%= current_user.profile.username %>
                <img src="<%= current_user.profile.avatar_url.presence || 'https://via.placeholder.com/40' %>" 
                  alt="Avatar" 
                  width="35" 
                  height="35" 
                  style="border-radius: 50%; object-fit: cover; border: 2px solid white;">
              </button>
            <% end %>
          </li>
          <li class="nav-item">
            <%= link_to "Edit User", edit_user_registration_path, class: "nav-link btn btn-link btn-outline-secondary" %>
          </li>
          <li class="nav-item">
            <%= button_to "Sign Out", destroy_user_session_path, method: :delete, form_class: "d-inline", class: "nav-link btn btn-link btn-outline-danger", data: { turbo: false } %>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Sign Up", new_user_registration_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>

    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "RedSocial" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet">

    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %> 
  </head>

  <body>
    <%= render 'layouts/navbar' %>
    <% if flash[:alert] %>
      <div class="alert alert-danger">
        <%= flash[:alert] %>
      </div>
    <% end %>
    <%= yield %>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
  </body>
</html>